export const intelligenceTypes = [
  {
    name: "Logic",
    icon: "/mi_icons/logictoanhoc.png",
    color: "from-blue-500 to-blue-300",
    bgColor: "bg-blue-100",
    borderColor: "border-blue-200",
    description:
      "Khả năng phân tích vấn đề, tư duy số học và giải quyết vấn đề logic",
    famousFigures: "Albert Einstein, Stephen Hawking, Marie Curie",
    careers: "Nhà toán học, lập trình viên, nhà khoa học, kỹ sư",
  },
  {
    name: "Ngôn ngữ",
    icon: "/mi_icons/linguistic.png",
    color: "from-green-500 to-green-300",
    bgColor: "bg-green-100",
    borderColor: "border-green-200",
    description: "Khả năng sử dụng ngôn từ hiệu quả, cả viết lẫn nói",
    famousFigures: "William Shakespeare, Jane Austen, J.K. Rowling",
    careers: "Nhà văn, nhà báo, luật sư, biên tập viên",
  },
  {
    name: "Không gian",
    icon: "/mi_icons/spatial.png",
    color: "from-purple-500 to-purple-300",
    bgColor: "bg-purple-100",
    borderColor: "border-purple-200",
    description:
      "Khả năng hình dung, tưởng tượng không gian và tư duy bằng hình ảnh",
    famousFigures: "Pablo Picasso, Frank Lloyd Wright, Leonardo da Vinci",
    careers: "Kiến trúc sư, họa sĩ, nhiếp ảnh gia, nhà thiết kế",
  },
  {
    name: "Vận động",
    icon: "/mi_icons/bodily.png",
    color: "from-red-500 to-red-300",
    bgColor: "bg-red-100",
    borderColor: "border-red-200",
    description:
      "Khả năng điều khiển cơ thể và thao tác vật thể một cách khéo léo",
    famousFigures: "Michael Jordan, Simone Biles, Bruce Lee",
    careers: "Vận động viên, diễn viên, bác sĩ phẫu thuật, thợ thủ công",
  },
  {
    name: "Âm nhạc",
    icon: "/mi_icons/musical.png",
    color: "from-yellow-500 to-yellow-300",
    bgColor: "bg-yellow-100",
    borderColor: "border-yellow-200",
    description: "Khả năng cảm thụ, sáng tác và biểu diễn các yếu tố âm nhạc",
    famousFigures: "Mozart, Beyoncé, Bob Marley",
    careers: "Nhạc sĩ, ca sĩ, nhạc công, nhà sản xuất âm nhạc",
  },
  {
    name: "Xã hội",
    icon: "/mi_icons/interpersonal.png",
    color: "from-pink-500 to-pink-300",
    bgColor: "bg-pink-100",
    borderColor: "border-pink-200",
    description: "Khả năng tương tác, thấu hiểu và làm việc với người khác",
    famousFigures: "Oprah Winfrey, Nelson Mandela, Dalai Lama",
    careers: "Giáo viên, nhà tâm lý học, nhân viên xã hội, nhà ngoại giao",
  },
  {
    name: "Nội tâm",
    icon: "/mi_icons/intrapersonal.png",
    color: "from-indigo-500 to-indigo-300",
    bgColor: "bg-indigo-100",
    borderColor: "border-indigo-200",
    description:
      "Khả năng hiểu rõ bản thân, nhận thức về giá trị và cảm xúc cá nhân",
    famousFigures: "Sigmund Freud, Virginia Woolf, Plato",
    careers: "Nhà triết học, nhà văn, nhà tâm lý học, nhà tư vấn",
  },
  {
    name: "Thiên nhiên",
    icon: "/mi_icons/naturalist.png",
    color: "from-teal-500 to-teal-300",
    bgColor: "bg-teal-100",
    borderColor: "border-teal-200",
    description: "Khả năng nhận biết và phân loại các yếu tố trong tự nhiên",
    famousFigures: "Charles Darwin, Jane Goodall, David Attenborough",
    careers: "Nhà sinh vật học, nhà bảo tồn, nông dân, nhà khí tượng học",
  },
  {
    name: "Triết học",
    icon: "/mi_icons/existential.png",
    color: "from-gray-500 to-gray-300",
    bgColor: "bg-gray-100",
    borderColor: "border-gray-200",
    description: "Khả năng tư duy trừu tượng về các vấn đề hiện sinh, triết lý",
    famousFigures: "Socrates, Friedrich Nietzsche, Simone de Beauvoir",
    careers: "Triết gia, nhà thần học, nhà văn, giáo sư đại học",
  },
];
