export const questionsMBTI = [
  "1. Trong một buổi tiệc, bạn sẽ:",
  "2. Bạn thiên về:",
  "3. Điều gì khiến bạn cảm thấy tệ hơn?",
  "4. Bạn thấy ấn tượng hơn bởi:",
  "5. Bạn dễ bị thuyết phục hơn bởi những sự việc:",
  "6. Bạn thích làm việc:",
  "7. Khi lựa chọn, bạn thường:",
  "8. Tại các buổi gặp mặt, bạn sẽ:",
  "9. Tuýp người nào sẽ thu hút bạn hơn?",
  "10. Bạn hứng thú hơn với những sự việc:",
  "11. Bạn thường đánh giá người khác dựa trên:",
  "12. Khi tiếp cận người khác, bạn thường đánh giá họ dựa trên góc nhìn nào?",
  "13. Bạn thường là người:",
  "14. Sau khi trải qua một kỳ thi, bạn thường:",
  "15. Trong nhóm, bạn thường là người:",
  "16. Cách bạn giải quyết những công việc thường ngày là:",
  "17. Theo bạn, các nhà văn nên:",
  "18. Điều gì thu hút bạn hơn?",
  "19. Bạn cảm thấy thoải mái hơn khi đưa ra nhận xét:",
  "20. Bạn thích những điều:",
  "21. Một phút thật lòng với bản thân nhé. Bạn là người:",
  "22. Khi nói chuyện điện thoại, bạn:",
  "23. Theo bạn, các sự việc và hiện tượng:",
  "24. Những người có tầm nhìn xa:",
  "25. Bạn là người:",
  "26. Bạn cảm thấy tồi tệ hơn khi đối mặt với:",
  "27. Theo bạn, quyết định nên được đưa ra:",
  "28. Khi đi mua sắm, bạn thích cảm giác nào hơn?",
  "29. Trong công ty, bạn là người:",
  "30. Với những kiến thức, quy luật đã được xã hội công nhận, bạn sẽ:",
  "31. Theo bạn, trẻ em thường không:",
  "32. Khi mua xe hơi, bạn nghĩ yếu tố nào quan trọng hơn?",
  "33. Tính cách của bạn nghiêng về:",
  "34. Khả năng nào đáng khâm phục hơn?",
  "35. Bạn mong muốn điều gì hơn ở cấp trên?",
  "36. Khi đối mặt với những vấn đề mới, bạn thường cảm thấy:",
  "37. Tính cách của bạn thiên về:",
  "38. Bạn sẽ quan tâm hơn đến:",
  "39. Điều gì làm bạn thoải mái hơn?",
  "40. Bạn sẽ lựa chọn công việc nào?",
  "41. Bạn thích được điều hướng công việc theo cách:",
  "42. Bạn thường tìm kiếm những điều:",
  "43. Bạn thường kết giao:",
  "44. Điều gì ảnh hưởng tới quyết định của bạn nhiều hơn?",
  "45. Bạn thấy hứng thú hơn với việc:",
  "46. Bạn thường được tán thưởng vì:",
  "47. Bạn thấy điều gì giá trị hơn ở bản thân mình?",
  "48. Bạn đánh giá cao:",
  "49. Bạn thấy nhẹ nhõm hơn:",
  "50. Bạn đánh giá bản thân là người như thế nào?",
  "51. Bạn có xu hướng tin tưởng vào:",
  "52. Bạn thường:",
  "53. Bạn thấy ấn tượng hơn khi tiếp xúc với một người:",
  "54. Bạn đánh giá tính cách nào cao hơn?",
  "55. Theo bạn, mọi chuyện sẽ diễn ra hợp lý hơn nếu:",
  "56. Trong một mối quan hệ:",
  "57. Khi có số lạ gọi tới điện thoại của bạn, bạn sẽ:",
  "58. Bạn đánh giá cao khả năng của mình hơn khi:",
  "59. Bạn bị thu hút hơn với điều gì?",
  "60. Bạn không thích những người:",
  "61. Bạn thuộc tuýp người:",
  "62. Trước một chuyến đi chơi, bạn thường:",
  "63. Trong công việc, bạn thường:",
  "64. Bạn nghĩ mình là người:",
  "65. Khi viết lách, bạn có xu hướng:",
  "66. Là một cấp trên, bạn cảm thấy điều gì khó hơn?",
  "67. Bạn cảm thấy mình cần trở nên:",
  "68. Điều gì khiến bạn khó chấp nhận hơn?",
  "69. Bạn sẽ lựa chọn:",
  "70. Phong cách làm việc của bạn là gì?",
];
