export const questionsMI = [
  "1. Tôi học tốt nhất bằng cách tự rèn luyện kỹ năng, hơn là đọc về nó hay có người khác chỉ",
  "2. Tôi thích xem phim kinh dị, phiêu lưu hay mạo hiểm",
  "3. Tôi có thể tháo lắp các đồ cơ khí, đồ gia dụng và biết cách sửa chúng",
  "4. Tôi không thể ngồi yên trong một thời gian dài, luôn phải cử động.",
  "5. Tôi giỏi việc ném và bắt",
  "6. Tôi khéo tay và thích làm những thứ như đồ handmade hay đồ mộc, đồ thủ công, …",
  "7. Tôi luôn mơ ước trở thành một nhạc sĩ hay ca sĩ",
  "8. Tôi có một bộ sưu tập âm nhạc ấn tượng mà tôi không thể thiếu được",
  "9. Tôi có chơi ít nhất 1 nhạc cụ",
  "10. Tôi có thể hát theo giai điệu và chỉ ra những nốt bị lệch tông",
  "11. Tôi thích rất nhiều các thể loại âm nhạc và có thể cảm nhận nhiều phong cách/ nhạc sĩ khác nhau",
  "12. Tôi thường có một bài hát, một âm thanh hay một đoạn nhạc ở trong đầu",
  "13. Thú nuôi của tôi cũng là bạn thân nhất của tôi - tôi không chịu được khi thiếu chúng",
  "14. Tôi thường xuyên tái chế và cố gắng tiết kiệm lượng nước và điện",
  "15. Bạn bè nghĩ tôi trồng cây rất mát tay",
  "16. Tôi thường nhận ra những kiến thức khoa học trong cuộc sống hàng ngày",
  "17. Tôi có thể dễ dàng phân biệt các loại cây và động vật khác nhau",
  "18. Tôi thích đi ra ngoài và còn thích hơn khi đi xa, ra khỏi thành phố",
  "19. Tôi thích nhìn thấy các bản vẽ hay biểu đồ về cách mọi thứ hoạt động",
  "20. Tôi thích chụp ảnh",
  "21. Tôi có thể hình dung ra các đồ vật từ nhiều góc nhìn khác nhau",
  "22. Tôi nhạy cảm với màu sắc và tính thẩm mỹ",
  "23. Tôi có rất nhiều tranh ảnh trong nhà hay trong máy tính cá nhân",
  "24. Tôi thường ghi nhớ / tưởng tượng ra các đoạn phim mình ưa thích",
  "25. Tôi luôn hỏi 'Tại sao,' thay vì 'Cái gì' hay 'Thế nào'",
  "26. Tôi thấy hứng thú với những câu hỏi triết học như 'Ý nghĩa cuộc sống là gì?'",
  "27. Tôi thường nghĩ về ý nghĩa của các sự kiện hay các câu hỏi",
  "28. Tôi thích tìm hiểu những vấn đề về tiến hóa, thiên văn học, triết học",
  "29. Bạn bè nghĩ tôi suy nghĩ quá nhiều",
  "30. Tôi thích xem phim tài liệu về các triết gia vĩ đại và các cuộc tranh luận triết học",
  "31. Tôi thích đọc, hoặc tham gia các phiên tranh biện hay thảo luận",
  "32. Tôi có một tủ sách mà không thể sống thiếu chúng",
  "33. Tôi giỏi các trò chơi ô chữ, câu đố và trò chơi chữ khác",
  "34. Tôi bịa chuyện rất dễ dàng",
  "35. Tôi có thể học ngoại ngữ dễ dàng",
  "36. Tôi luôn mơ ước được trở thành nhà văn hay biên tập viên",
  "37. Mọi người thường tìm đến tôi để trò chuyện",
  "38. Tôi thích đến các buổi tiệc hay sự kiện xã hội hơn là ngồi ở nhà một mình",
  "39. Tôi cảm thấy buồn khi người khác buồn",
  "40. Tôi là con người của xã hội (hòa đồng, quảng giao, …)",
  "41. Tôi dễ nhận ra cảm xúc thông qua ngôn ngữ cơ thể của người khác",
  "42. Mọi người nghĩ rằng tôi thích nhận được sự chú ý, thích là trung tâm",
  "43. Tôi thích tìm hiểu về bản thân và các cảm xúc của mình",
  "44. Tôi thích dành thời gian ở một mình",
  "45. Tôi hiểu cảm xúc của mình và biết mình sẽ phản ứng như thế nào trong các tình huống khác nhau",
  "46. Tôi thích làm việc một mình hơn là làm theo nhóm",
  "47. Tôi là một người cô đơn",
  "48. Tôi thích làm các bài tập để tìm hiểu về bản thân như trắc nghiệm tích cách",
  "49. Tôi ghi nhớ các sự kiện, số liệu, và công thức một cách dễ dàng",
  "50. Tôi hay đưa ra lời giải thích hợp lý cho các sự kiện",
  "51. Bạn bè nghĩ tôi có một bộ não như máy tính",
  "52. Tôi có thể làm toán nhẩm trong đầu",
  "53. Tôi không thể hiểu được những người không có logic và lý trí",
  "54. Tôi thích tìm hiểu về cách mọi thứ hoạt động ra sao",
  "55. Tôi rất hay ghi chú, lập danh sách để ghi nhớ, thay vì chỉ dựa vào trí nhớ của bản thân",
  "56. Tôi hay nghi ngờ những thông tin mình nhận được, ít khi tin ngay lập tức",
  "57. Tôi thấy chán chường khi ở một mình và không cần những khoảng thời gian một mình",
  "58. Tôi thường chấp nhận mọi thứ như hiện trạng của chúng và ít khi cảm thấy không thỏa mãn với hiện tại",
  "59. Tôi giữ cho không gian quanh mình được sạch sẽ, không bao giờ để đồ đạc lung tung",
  "60. Tôi nghĩ lời nhận xét 'giống robot' là một sự xúc phạm, tôi không muốn hướng tới việc tư duy như cỗ máy",
  "61. Tôi thường tràn đầy năng lượng và không bao giờ ủ rũ",
  "62. Tôi thích làm những bài kiểm tra trắc nghiệm hơn là viết luận",
  "63. Tôi thấy thoải mái với sự hỗn loạn, hơn là tính có tổ chức, có sắp xếp",
  "64. Tôi thường dễ cảm thấy tổn thương và khó chịu đựng được chỉ trích",
  "65. Tôi làm việc tốt nhất khi là thành viên của một nhóm, hơn là khi làm việc một mình",
  "66. Tôi tập trung vào những việc thực tiễn ở hiện tại, thay vì nghĩ tới những kế hoạch tương lai",
  "67. Tôi thường lên kế hoạch cho tương lai xa chứ không để sát nút rồi mới lên kế hoạch",
  "68. Tôi cần sự tôn trọng từ người khác hơn là cảm tình của họ",
  "69. Sau mỗi buổi tiệc tùng, tôi thường kiệt sức thay vì sung mãn",
  "70. Tôi rất dễ hòa đồng và ít khi bị cô lập",
  "71. Tôi thích sự tự do, không cần kế hoạch hay cam kết gì cụ thể",
  "72. Tôi muốn làm giỏi việc sửa chữa các đồ vật hơn là thay đổi con người",
  "73. Tôi thường bày tỏ quan điểm nhiều hơn là im lặng lắng nghe",
  "74. Tôi thường đơn thuần là mô tả các sự việc, nhiều hơn là nói về ý nghĩa hay tác động của chúng",
  "75. Tôi thường hoàn thành công việc sớm nhất có thể thay vì trì hoãn chúng",
  "76. Tôi thường hành động theo trái tim mình hơn là theo cái đầu",
  "77. Tôi thường ở nhà nhiều hơn là đi ra ngoài",
  "78. Tôi thích việc quan sát tổng quan hơn là tập trung vào chi tiết",
  "79. Tôi giỏi ứng biến hơn là lên kế hoạch",
  "80. Tôi nghĩ công lý không nên dựa trên sự thông cảm",
  "81. Tôi khó có thể hét to được nên rất khó gọi người khác khi họ ở khoảng cách xa",
  "82. Tôi tin tưởng vào những lý thuyết khoa học hơn là kinh nghiệm cá nhân",
  "83. Tôi dành nhiều thời gian để làm việc hơn là thư giãn, đi chơi",
  "84. Tôi thấy không thoải mái mỗi khi cảm xúc dâng trào, dù là của bản thân hay người khác",
  "85. Tôi thích việc thể hiện bản thân trước nhiều người, không tránh né việc nói trước đông người",
  "86. Tôi thích được biết các thông tin chi tiết và cụ thể, ví dụ như có những ai, ở đâu, làm gì, vào lúc nào, etc., và ít khi quan tâm đến lý do tại sao",
];