export { default as CompanyHero } from "./CompanyHero";
export { default as CompanyTabs } from "./CompanyTabs";
export { default as CompanyOverview } from "./CompanyOverview";
export { default as CompanyJobs } from "./CompanyJobs";
export { default as CompanyPhotos } from "./CompanyPhotos";
export { default as CompanySidebar } from "./CompanySidebar";
export { default as CompanyLoading } from "./CompanyLoading";
export { default as CompanyNotFound } from "./CompanyNotFound";
export { default as CompanyMap } from "./CompanyMap";
